name: BuildSomething
main: net.yzimroni.buildsomething2.BuildSomethingPlugin
version: 0.1
description: BuildSomething 2 plugin.
softdepend: [WorldEdit, WorldGuard, ProtocolLib, Citizens, Party, CommandManager]
authors: [yzimroni]
commands:
  game:
    description: game
    aliases: [bs, buildsomething]
  money:
    description: game
    aliases: [m]
  stats:
    description: game
  plot:
    description: game
  plottp:
    description: game