name: BuildSomething
main: net.yzimroni.buildsomething2.BuildSomethingPlugin
version: 0.1
description: BuildSomething 2 plugin.
softdepends: [WorldEdit, WorldGuard, ProtocolLib, Citizens, Party]
authors: [yzimroni]
commands:
  game:
    description: game
  money:
    description: game
  m:
    description: game
  bs:
    description: game
  buildsomething:
    description: game
  stats:
    description: game
  plot:
    description: game
  plottp:
    description: game